### ISSUE TITLE
Cached `cls_onig_regexp` / `cls_onig_match_data` globals corrupt regex behavior across mrb_states (e.g. with `mruby-thread`)

### ISSUE THREAD

**Issue by vobloeb** [mattn/mruby-onig-regexp#129]
## Summary

Commits [`cf9d335`](https://github.com/mattn/mruby-onig-regexp/commit/cf9d335) and [`790ba17`](https://github.com/mattn/mruby-onig-regexp/commit/790ba17) (on `master` HEAD `3389bae`) replaced per-call `mrb_class_get(mrb, "OnigRegexp")` / `mrb_class_get(mrb, "OnigMatchData")` lookups with **file-scope, non-`static`, non-thread-local globals**:

```c
// src/mruby_onig_regexp.c, ~line 63-64
struct RClass* cls_onig_regexp;
struct RClass* cls_onig_match_data;
```

These globals are assigned **inside `mrb_mruby_onig_regexp_gem_init`** to the `RClass*` of the *just-defined* `OnigRegexp` / `OnigMatchData` classes — i.e. to pointers into *that* `mrb_state`'s heap:

```c
cls_onig_regexp     = mrb_define_class(mrb, "OnigRegexp",     mrb->object_class);
cls_onig_match_data = mrb_define_class(mrb, "OnigMatchData",  mrb->object_class);
```

`mrb_define_class` returns a `RClass*` allocated **inside `mrb`'s gc-managed heap**. Different `mrb_state`s have different heaps, so the same `cls_onig_regexp` global cannot be valid for more than one VM at a time.

When a host application creates a second `mrb_state` (e.g. via [`mruby-thread`](https://github.com/mattn/mruby-thread)'s `Thread.new`, which calls `mrb_open()` and re-runs every gem's `gem_init` in the child VM), the `gem_init` for `mruby-onig-regexp` overwrites the globals with the **child VM's** class pointers. The **parent VM** then reads these globals through code paths like:

```c
// onig_match_common, ~line 247
if (mrb_class_get_id(mrb, MRB_SYM(Regexp)) == cls_onig_regexp && ...) {
    onig_gv_set(mrb, MISMATCH_NIL_OR(match_value));
}
```

`mrb_class_get_id(mrb_parent, MRB_SYM(Regexp))` resolves the `Regexp` constant *inside the parent VM* → returns parent's `OnigRegexp` class. The comparison is against `cls_onig_regexp`, which now points to the **child's** `OnigRegexp` class (different heap, different pointer). The gate fails → `onig_gv_set` is never called → `$~` / `$1`-`$9` are not set after the match → subsequent `case x when /re/ then $1.X` raises `NoMethodError: undefined method 'X' for nil`.

`mrb_obj_iv_get(mrb_parent, (struct RObject*)cls_onig_regexp, ...)` and similar calls elsewhere in the file are an even bigger hazard: they read instance variables off the child VM's class object *while passing the parent's `mrb_state`* — at minimum incorrect semantically (different `@last_match` / `@set_global_variables`), at worst UB if the child VM's GC has moved or freed the object.

## Repro

Minimal sketch using `mruby-thread`:

```ruby
case "k=v"
when /^(\w+)=(.+)$/ then puts "parent: #{$1.inspect}/#{$2.inspect}"  # → "k"/"v" — fine
end

t = Thread.new { sleep 0.1 }     # mruby-thread Thread.new → mrb_open in child
sleep 0.05                       # let child's gem_init run
case "k=v"
when /^(\w+)=(.+)$/ then puts "parent after Thread.new: #{$1.inspect}/#{$2.inspect}"  # → nil/nil
end
t.join
```

(Race-sensitive — depending on which thread's `mrb_open` ran last, the bug may not show on every run. Spawning many threads or holding them alive widens the window.)

## Root cause

`RClass*` is an `mrb_state`-scoped heap pointer. Caching it in a process-global is unsound across VMs.

`mrb_sym` (i.e. the `static mrb_sym sym_dollar_tilde;` cache lower in the same file) is *almost* OK on builds with presym (mruby 3.3+ default) because the precomputed sym IDs are shared across VMs — but on builds with presym disabled, `mrb_intern_lit(child_vm, "$~")` and `mrb_intern_lit(parent_vm, "$~")` may produce different integer IDs, so the cached value of `sym_dollar_tilde` (last writer wins) becomes wrong for the other VM. Same hazard, smaller blast radius.

## Suggested fix

Drop the caches and restore per-call lookups (the code that existed before `cf9d335` / `790ba17`):

```c
// instead of:  cls_onig_regexp
mrb_class_get_id(mrb, MRB_SYM(OnigRegexp))         // or mrb_class_get(mrb, "OnigRegexp")
// instead of:  cls_onig_match_data
mrb_class_get_id(mrb, MRB_SYM(OnigMatchData))
```

`mrb_class_get_id` is O(1) hash lookup on `mrb->object_class`'s iv table — single-digit nanoseconds per call. The micro-optimization is not worth the multi-VM hazard.

If perf matters, an alternative is to attach the class pointer **per-VM** — e.g. cache it on `mrb->object_class` as an iv (`mrb_obj_iv_set(mrb, (RObject*)mrb->object_class, MRB_IVSYM(_onig_regexp_cls), …)`), or stash it on `mrb_state` via the `userdata` slot. But that's strictly more code than the simple `mrb_class_get_id` per-call.

The `static mrb_sym sym_dollar_*` array can be left as-is for builds with presym (i.e. mruby 3.3+ default), or moved to per-call `mrb_intern_lit` to be safe on legacy/no-presym builds.

## Versions

- `mruby-onig-regexp`: `3389bae` (current `master`). Last good (per our bisect): `bcfa173e`.
- `mruby`: reproduces on 3.3 and 4.0.
- `mruby-thread`: any.

Happy to send a PR. Thanks for the gem.

**Comment by tatsuhiro-t** [comment]
@mattn 
This also hits our system and completely destroyed the use case of one mrb_state per thread pattern.  Please revert https://github.com/mattn/mruby-onig-regexp/commit/790ba17.  Performance improvements that breaks multi thread safety is not really a good idea.

**Comment by mattn** [comment]
I opened #131 for this. Rather than fully reverting, it restores per-call `mrb_class_get_id()` lookups as the default (safe across multiple `mrb_state`s) and keeps the cached fast path behind an opt-in `MRB_ONIG_REGEXP_CACHE_CLASS` build macro for single-`mrb_state` builds. Both builds pass the full test suite.

Does this approach work for you, or would you prefer a straight revert of #121? cc @vobloeb @tatsuhiro-t

**Comment by tatsuhiro-t** [comment]
@mattn Thank you for the quick response.  For my use case, these static initializations of global variables should also be removed (see https://github.com/mattn/mruby-onig-regexp/blob/92775036121c4fde18f0933f8ee24a2faf3d0025/src/mruby_onig_regexp.c#L1250-L1262).
mrb_open eventually calls mrb_mruby_onig_regexp_gem_init and if it is called simultaneously from multiple threads, we are in trouble.  Perhaps, do these initializations behind MRB_ONIG_REGEXP_CACHE_CLASS too?

**Comment by mattn** [comment]
Good catch — done. #131 now gates the `sym_dollar_*` symbol caches behind the same macro too, so by default `gem_init` no longer writes any process globals (no write-write race when `mrb_open()` runs concurrently, and the symbols are resolved per call against the right `mrb_state`). The macro is renamed to `MRB_ONIG_REGEXP_CACHE` since it now covers both the class and symbol caches. Verified that the default build emits no cached globals at all, and both builds pass the full test suite.

**Comment by tatsuhiro-t** [comment]
@mattn Thank you.  PR looks good for avoiding crashes in multi thread use.  Ideally, we need to clean it up a bit more.  For instance:

https://github.com/mattn/mruby-onig-regexp/pull/131/changes#diff-52af0392719e5a5e514a5dc10a06abe3b85ebf6202e0c91a184490205f17eba3R1188

This function does bunch of stuff, but if the macro is off, this is basically noop with some latency added.  It would be very nice to clearly separate global and non-global things so that we do not mess these things up in the future.

We should also make sure that we do not have regression in term of the performance before #121 and after the proposed patch with the macro off.

**Comment by vobloeb** [comment]
#130 is related: although the spot is different it is also about globals in `mruby-onig-regexp` which break `mruby-thread`

**Comment by mattn** [comment]
Thanks for the review.

**Performance:** I benchmarked the macro-off build on a regex-heavy loop (`=~` with `$~`/`$1`/`$2`, `scan`, `gsub`; 300k iterations; identical results across all builds).

| build | best of 5 |
|---|---|
| pre-#121 (`0b86861`) | 6.23s |
| this PR, macro **off** (default) | 6.10s |
| this PR, macro **on** (`MRB_ONIG_REGEXP_CACHE`) | 6.07s |

Macro-off vs macro-on are within run-to-run noise, and both are on par with the pre-#121 code. The per-call `mrb_class_get_id()` / `mrb_intern_lit()` are O(1) and negligible next to the actual matching and allocation, so there is no measurable regression from defaulting to per-call lookups.

**Separation:** The cached vs per-call decision is already confined to a single `#ifdef MRB_ONIG_REGEXP_CACHE` block at the top of the file — the function bodies only go through the `ONIG_SYM_*` / `ONIG_REGEXP_CLASS` accessors and never touch a process global directly, and with the macro off `gem_init` writes no globals at all. I'd prefer to keep that structure for this fix rather than reshape the surrounding code; it keeps the diff focused and leaves a single place to audit for cross-VM-unsafe state. Happy to revisit a deeper cleanup separately if you feel strongly.

**Comment by tatsuhiro-t** [comment]
Looks good to me.  Thank you.

**Comment by mattn** [comment]
Merged https://github.com/mattn/mruby-onig-regexp/pull/131

**Comment by mattn** [comment]
So closable?
